## docker compose example
## based on https://github.com/overleaf/overleaf/blob/old-master/docker-compose.yml

services:
  web:
    restart: always
    image: ghcr.io/jerome-labidurie/overleaf-full:5.5.2
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - 8086:80
    links:
      - mongo
      - redis
    volumes:
      # ChangeMe: data volmume mount
      - /mnt/overleaf/data:/var/lib/overleaf
    labels:
      # if you use getwud https://github.com/getwud/wud
      wud.tag.include: "^\\d+\\.\\d+\\.\\d+$$"
    environment:
        OVERLEAF_APP_NAME: Overleaf Community Edition
        OVERLEAF_MONGO_URL: mongodb://mongo/sharelatex
        # Same property, unfortunately with different names in
        # different locations
        OVERLEAF_REDIS_HOST: redis
        REDIS_HOST: redis

        ENABLED_LINKED_FILE_TYPES: 'url,project_file'

        # Enables Thumbnail generation using ImageMagick
        ENABLE_CONVERSIONS: 'true'

        # Disables email confirmation requirement
        EMAIL_CONFIRMATION_DISABLED: 'true'

        # temporary fix for LuaLaTex compiles
        # see https://github.com/overleaf/overleaf/issues/695
        TEXMFVAR: /var/lib/sharelatex/tmp/texmf-var

        # ChangeMe: your domaine
        OVERLEAF_SITE_URL: http://overleaf.example.com
        # ChangeMe: your instance name
        OVERLEAF_NAV_TITLE: My OverLeaf
        # ChangeMe: your email
        OVERLEAF_ADMIN_EMAIL: admin@axample.com

        UV_THREADPOOL_SIZE: 8

  mongo:
    # https://github.com/overleaf/overleaf/issues/1188#issuecomment-2236146523
    restart: always
    image: mongo:6.0.24
    expose:
      - 27017
    command: '--replSet overleaf'
    extra_hosts:
      # Required when using the automatic database setup for initializing the replica set.
      # This override is not needed when running the setup after starting up mongo.
      - mongo:127.0.0.1
    # ChangeMe: your user id:group
    user: 1024:100
    volumes:
      # ChangeMe: your data volume mount
      - /mnt/overleaf/mongo:/data/db:rw
    healthcheck:
      test: echo 'db.stats().ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
    labels:
      # if you use getwud https://github.com/getwud/wud
      wud.tag.include: "^5\\.\\d+\\.\\d+$$"

  mongo-init:
    restart: "no"
    image: mongo:6.0.24
    depends_on:
      mongo:
        condition: service_healthy
    entrypoint:
      [
          "mongosh",
          "--host",
          "mongo:27017",
          "--eval",
          'rs.initiate({_id: "overleaf", members: [{_id: 0, host: "mongo:27017"}]})',
      ]

  redis:
    restart: always
    image: redis:6.2.18
    expose:
      - 6379
    labels:
      # if you use getwud https://github.com/getwud/wud
      wud.tag.include: "^5\\.\\d+\\.\\d+$$"
    volumes:
      - redisdata:/data

volumes:
  redisdata:
